"""user_login & user_info

Revision ID: ddf568b63da2
Revises: 
Create Date: 2020-12-03 17:07:38.160276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf568b63da2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login_email'), 'user_login', ['email'], unique=True)
    op.create_index(op.f('ix_user_login_username'), 'user_login', ['username'], unique=True)
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('acc_num', sa.Integer(), nullable=False),
    sa.Column('cnic', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_login.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    op.drop_index(op.f('ix_user_login_username'), table_name='user_login')
    op.drop_index(op.f('ix_user_login_email'), table_name='user_login')
    op.drop_table('user_login')
    # ### end Alembic commands ###
